name: hmartfrontend
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_chat_ui: ^1.6.15
  audioplayers: ^6.1.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  audioplayers: ^6.1.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/SUPER_SECRET_ASSET.png
    - assets/sounds/580590_All-Star-8bit-Remix.mp3
